//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopy
    {
        public int BookCopiesID { get; set; }
        public int Book { get; set; }
        public int Library { get; set; }
        public Nullable<int> NumberOfCopies { get; set; }
    
        public virtual Book Book1 { get; set; }
        public virtual Library Library1 { get; set; }
    }
}
